### ISSUE TITLE
error run in mac Intel

### ISSUE THREAD

**Issue by daidi** [efJerryYang/uiohook-rs#2]
Compiling iohook v0.1.0 (/Users/dorothy/Work/iohook)
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u TVOS_DEPLOYMENT_TARGET -u XROS_DEPLOYMENT_TARGET LC_ALL="C" PATH="/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin:/Users/dorothy/.cargo/bin:/Users/dorothy/anaconda3/bin:/Users/dorothy/anaconda3/condabin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/dorothy/.cargo/bin:/usr/local/bin:/Users/dorothy/Tools/flutter/bin:/Users/dorothy/anaconda3/bin:/Users/dorothy/Library/Caches/.wasm-pack/.wasm-bindgen-cargo-install-0.2.92/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "x86_64" "-m64" "/var/folders/91/mbtqz2cn2fn8kr9cmpxztbfm0000gn/T/rustcsnjTn9/symbols.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.14u94o75hnel6ycb.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.1787ry22sc7yna6m.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.1vgglv2ttlmpjnq8.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.1xb8j2d9llxc5x3f.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.232idxdq3vfhyh40.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.25dvxob1jdfe0j10.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.2aeku2enefr0alat.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.2sgl659dbltzcx9m.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.2xxz2aasadwbmdkk.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.30c2lteoesvhkxwx.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.34tqony0vlp5vvbc.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.39y3vtkwzpir1x0v.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.3ne0icsicdxpyqku.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.3nh3utgsq0vvu91z.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.3v919bf49darmgh7.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.3ygvdzkhhoc312br.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.40244c017skc5fpk.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.43eqoaxzd4s1jj7g.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.43sezau0zib6ysgy.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.4epxxhb9jekliomw.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.4pp4ruhlwo64ynk7.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.4wlm18dlwr5wu3bk.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.4xnva1wi5iz3rf07.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.bfdblxwsimrfs1u.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.njhyzt24zy4opa2.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.p6l1wxowt9cu95y.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.r6grzfs9tj4w10e.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.rznp9ondip3v8vh.rcgu.o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f.3ehsh0y4wif0gxqu.rcgu.o" "-L" "/Users/dorothy/Work/iohook/target/debug/deps" "-L" "/Users/dorothy/.cargo/registry/src/mirrors.ustc.edu.cn-12df342d903acd47/uiohook-rs-0.2.0/libuiohook" "-L" "/Users/dorothy/Work/iohook/target/debug/build/uiohook-rs-42ca040bc5b6a1ce/out" "-L" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib" "/Users/dorothy/Work/iohook/target/debug/deps/liblibc-1755f2af5a850a36.rlib" "/Users/dorothy/Work/iohook/target/debug/deps/libthiserror-ec0c687e0c159997.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-85e77511d3e3991b.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-eafdc89bf8c2684d.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-473ec6507ab8ac34.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libmemchr-da05ae84e079b23a.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-49f48c8353cb63cf.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-796235596cf6de05.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-b608fa3804da184e.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-3f8aa96fd409fcfa.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-99e8bc8b90734e5d.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-5bde543e51b94788.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libminiz_oxide-8bb1d541b75e927b.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libadler-52c973eaba43f28d.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-1d23464efad515b4.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-429ede14115b4830.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-821915d3a4d69b7b.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-2350d8e656d53eda.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-58940dcec9080f3b.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-709ee95972af0293.rlib" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-5db7a0f312dea0af.rlib" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/dorothy/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/dorothy/Work/iohook/target/debug/deps/iohook-c4fa1932396b218f" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: ld: warning: object file (/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib[7](a7b946e507b60807-logger.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          ld: warning: object file (/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          ld: warning: object file (/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib[9](c7741b0c87314601-post_event.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          ld: warning: object file (/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib[10](c7741b0c87314601-system_properties.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          ld: warning: object file (/Users/dorothy/Work/iohook/target/debug/deps/libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)) was built for newer 'macOS' version (14.5) than being linked (14.0)
          Undefined symbols for architecture x86_64:
            "_CFDataGetBytes", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFDataGetLength", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFDictionaryCreate", referenced from:
                _is_accessibility_enabled in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
            "_CFEqual", referenced from:
                _process_key_pressed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _hook_run in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFMachPortCreateRunLoopSource", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFMachPortInvalidate", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRelease", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CFRunLoopAddObserver", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopAddSource", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopContainsObserver", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopContainsSource", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopGetCurrent", referenced from:
                _hook_run in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopGetMain", referenced from:
                _process_key_pressed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _hook_run in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopObserverCreate", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopObserverInvalidate", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopRemoveObserver", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopRemoveSource", referenced from:
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CFRunLoopRun", referenced from:
                _hook_run in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventCreateData", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventCreateKeyboardEvent", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventGetFlags", referenced from:
                _process_modifier_changed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventGetIntegerValueField", referenced from:
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_key_pressed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_key_released in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_modifier_changed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventGetLocation", referenced from:
                _process_button_pressed in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_button_released in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_mouse_moved in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_mouse_wheel in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventGetTimestamp", referenced from:
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventGetType", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventKeyboardGetUnicodeString", referenced from:
                _keycode_to_unicode in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
            "_CGEventSetFlags", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventSourceButtonState", referenced from:
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventSourceCreate", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventSourceFlagsState", referenced from:
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventSourceKeyState", referenced from:
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _initialize_modifiers in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                ...
            "_CGEventTapCreate", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_CGEventTapEnable", referenced from:
                _hook_event_proc in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_kCFAllocatorDefault", referenced from:
                _process_system_key in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _is_accessibility_enabled in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
            "_kCFBooleanTrue", referenced from:
                _is_accessibility_enabled in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
            "_kCFCopyStringDictionaryKeyCallBacks", referenced from:
                _is_accessibility_enabled in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
            "_kCFRunLoopDefaultMode", referenced from:
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _create_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
                _destroy_event_runloop_info in libuiohook_rs-af8d09bf6267a81e.rlib[8](c7741b0c87314601-input_hook.o)
            "_kCFTypeDictionaryValueCallBacks", referenced from:
                _is_accessibility_enabled in libuiohook_rs-af8d09bf6267a81e.rlib[11](c7741b0c87314601-input_helper.o)
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: could not compile `iohook` (bin "iohook") due to 1 previous error

**Comment by efJerryYang** [comment]
@daidi Added missing linkings for MacOS (`CoreFoundation` and `CoreGraphics`). It should compile now in `0.2.1`. Notice that the demo may not be working as expected on MacOS (from my quick test it just exited after starting, which may be related to the EOF thing). Please contribute a runnable demo for MacOS if you like.

```rust
"macos" => {
            build
                .file(libuiohook_dir.join("src/darwin/input_hook.c"))
                .file(libuiohook_dir.join("src/darwin/post_event.c"))
                .file(libuiohook_dir.join("src/darwin/system_properties.c"))
                .file(libuiohook_dir.join("src/darwin/input_helper.c"));
                // add the following two lines
                println!("cargo:rustc-link-lib=framework=CoreFoundation");
                println!("cargo:rustc-link-lib=framework=CoreGraphics");
        }
```
